### PR TITLE
Start many processes from single dworker process

### PR DESCRIPTION
**Pull request by mrocklin**
This adds an `--nprocesses` flag to `dworker`

### Example

```
$ dworker 127.0.0.1:8787 --ncores 1 --nprocesses 4
distributed.nanny - INFO - Start Nanny at:             192.168.20.114:36446
distributed.nanny - INFO - Start Nanny at:             192.168.20.114:47249
distributed.nanny - INFO - Start Nanny at:             192.168.20.114:42000
distributed.worker - INFO - Start worker at             192.168.20.114:47875
distributed.worker - INFO - Waiting to connect to       127.0.0.1:8787
distributed.nanny - INFO - Start Nanny at:             192.168.20.114:36962
distributed.worker - INFO - Start worker at             192.168.20.114:41985
distributed.worker - INFO - Waiting to connect to       127.0.0.1:8787
distributed.worker - INFO - Registered with center at:  127.0.0.1:8787
distributed.worker - INFO - Registered with center at:  127.0.0.1:8787
distributed.worker - INFO - Start worker at             192.168.20.114:59064
distributed.worker - INFO - Waiting to connect to       127.0.0.1:8787
distributed.worker - INFO - Start worker at             192.168.20.114:46390
distributed.worker - INFO - Waiting to connect to       127.0.0.1:8787
distributed.worker - INFO - Registered with center at:  127.0.0.1:8787
distributed.worker - INFO - Registered with center at:  127.0.0.1:8787
distributed.nanny - INFO - Nanny 192.168.20.114:36446 starts worker process 192.168.20.114:47875
distributed.nanny - INFO - Nanny 192.168.20.114:47249 starts worker process 192.168.20.114:41985
distributed.nanny - INFO - Nanny 192.168.20.114:42000 starts worker process 192.168.20.114:59064
distributed.nanny - INFO - Nanny 192.168.20.114:36962 starts worker process 192.168.20.114:46390
```

### Questions

We should think about `ncores` and `nprocesses` a bit.  Perhaps we should rename `ncores` to `nthreads` or `threads-per-process`?  Perhaps we should keep only `ncores` but add a `multiprocessing` flag instead?

What I did here is pretty much the most basic solution I could think of.  It's worth thinking about the desrired API a bit here.  It's not hard to change things.

cc @broxtronix

### CODE REVIEW

**Comment by broxtronix** [comment]
This looks awesome to me!  As far as the API goes, I think `nthreads-per-process` and `nprocesses` or `threads-per-process` and `num-processes` would probably be the least ambigious.   That said, I'm sort of a fan of `nthreads` and `nprocesses` for brevity.  I suppose clarity is probably more important than brevity, though, since these commands are usually going to be launched by scripts rather than human beings.

Either way, I really like the ability to independently specify the number of threads per process and the number of processes.  Having this fine-grained control is likely only for performance tuning geeks (like me), but I can imagine certain workloads where you might want to smoothly adjust the mixture from fully threaded to fully multi-process parallelism.  If it were a lot of extra work to have both knobs to twiddle, then I would say it wasn't worth it at the moment, but it looks like this fits nicely into your existing abstractions.

**Comment by mrocklin** [comment]
OK, I'm using `nthreads` and `ncores` for now.  I've expanded the help strings around the keywords a bit.

I've also set `nthreads` to scale inversely with `nprocs` if not specified (so that `--nprocs 2` halves the default for `--nthreads`)

**Comment by broxtronix** [comment]
That sounds great.  Once you merge this in, I can make some final tweaks to the `dcluster` PR to make use of these new command line arguments!  I imagine the cleanest way to do that will be to pull in the changes from the master branch, but with the --rebase option so that the commit history is properly sorted?

**Comment by mrocklin** [comment]
That might be cleanest but I personally don't care that much.

**Pull request merged**
