### PR TITLE
Executor compute

### PR DESCRIPTION
**Pull request by mrocklin**
Add executor.compute method

```python
    def compute(self, *args, sync=False):
        """ Compute dask collections on cluster

        Parameters
        ----------
        args: iterable of dask objects
            Collections like dask.array or dataframe or dask.value objects
        sync: bool (optional)
            Returns Futures if False (default) or concrete values if True

        Returns
        -------
        Tuple of Futures or concrete values

        Examples
        --------

        >>> from dask import do, value
        >>> from operator import add
        >>> x = dask.do(add)(1, 2)
        >>> y = dask.do(add)(x, x)
        >>> xx, yy = executor.compute(x, y)  # doctest: +SKIP
        >>> xx  # doctest: +SKIP
        <Future: status: finished, key: add-8f6e709446674bad78ea8aeecfee188e>
        >>> xx.result()  # doctest: +SKIP
        3
        >>> yy.result()  # doctest: +SKIP
        6
        """
```

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @broxtronix

**Comment by mrocklin** [comment]
This depends on a small change within dask.  https://github.com/blaze/dask/pull/869

**Comment by broxtronix** [comment]
Cool!  I just pulled in the changes to both Blaze and Distributed.  The new `compute()` methods works as described, returning a Futures object (or list of them) instead of a finished computation.  Futures are nice. 

Progress bar doesn't work quite yet, but I imagine you are still working on that.  Currently this:
```
results = executor.compute(*colormapped_images);
distributed.diagnostics.progress(results)
```
produces this error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-4febf5eb5c1f> in <module>()
      4 #with distributed.diagnostics.progress(colormapped_images, notebook = False):
      5 results = executor.compute(*colormapped_images);
----> 6 distributed.diagnostics.progress(results)

/Users/broxton/anaconda3/lib/python3.5/site-packages/distributed-1.5.0-py3.5.egg/distributed/diagnostics.py in progress(futures, notebook, multi)
    349             bar = MultiProgressWidget(futures)
    350         else:
--> 351             bar = ProgressWidget(futures)
    352     else:
    353         bar = TextProgressBar(futures)

/Users/broxton/anaconda3/lib/python3.5/site-packages/distributed-1.5.0-py3.5.egg/distributed/diagnostics.py in __init__(self, keys, scheduler, minimum, dt)
    260 class ProgressWidget(Progress):
    261     def __init__(self, keys, scheduler=None, minimum=0, dt=0.1):
--> 262         Progress.__init__(self, keys, scheduler, minimum, dt)
    263         from ipywidgets import FloatProgress
    264         self.bar = FloatProgress(min=0, max=1, description='0.0s')

/Users/broxton/anaconda3/lib/python3.5/site-packages/distributed-1.5.0-py3.5.egg/distributed/diagnostics.py in __init__(self, keys, scheduler, minimum, dt)
     88             if time.time() > start + 1:
     89                 raise ValueError("Keys not found: %s" % str(keys -
---> 90                     scheduler.in_play))
     91 
     92         self._start_time = default_timer()

ValueError: Keys not found: {(<Future: status: finished, key: finalize-80bbba60de0d198544e88b92df8d7d4a>, <Future: status: finished, key: finalize-323d0068d294131624212d74c376877d>, <Future: status: finished, key: finalize-b66f2cf495a2e2ce1a830bb055a5452d>, <Future: status: finished, key: finalize-d2cc247a160c5e4ddac4723f2e44a59a>, <Future: status: finished, key: finalize-6dde2f2942c0d30afb37b5a5ffc7eb60>, <Future: status: finished, key: finalize-2552974878a62eac0585b123ca6ceebb>, <Future: status: finished, key: finalize-6d8141e4f47e9862088dcbe06ac17077>, <Future: status: finished, key: finalize-5d068359e49c6c6b458a3dbf8ca0fb46>, <Future: status: finished, key: finalize-f7b8a73fd99733268dffef45f8e246ae>, <Future: status: finished, key: finalize-e36c0052c4df250eded67712aa2c4b85>, <Future: status: finished, key: finalize-93fc3b0b117a18697f9900f1b1dcef19>, <Future: status: finished, key: finalize-57417635ed2ec08158e2674508622c74>, <Future: status: finished, key: finalize-cc6a6e8f7137887dbbe90a6b32c02b23>, <Future: status: finished, key: finalize-40d9b640e5a97bf1889e70935fd5ce31>, <Future: status: finished, key: finalize-7d034e511efbcb605e4278e271aaede2>, <Future: status: finished, key: finalize-edf3e6fdd5495c03988eaf850aca4a04>, <Future: status: finished, key: finalize-ebe3305c8b34a685b74ea3fede6dfbba>, <Future: status: finished, key: finalize-92a3518df496a74f94da903b187e9974>, <Future: status: finished, key: finalize-dbe0e6af1336a7e6710606d06d6f86e0>, <Future: status: finished, key: finalize-29440e905e7a633ec50f86fe8f6ef07d>)}
```
although 
```
distributed.diagnostics.progress(results[0])
```
does indeed work!  (So, it's just the list of Futures that doesn't quite work yet.)

**Comment by mrocklin** [comment]
Ah, `progress` only expands out sets and lists, not tuples.  Compute produces tuples.  

I'll have to change one or the other to make the design more consistent.

The following should work immediately though

```python
>>> progress(list(results))
```

I also recommend playing with the `multi=True` option

```python
>>> progress(list(results), multi=True)
```

It's a bit fancier and also a bit less tested.

**Comment by mrocklin** [comment]
Compute now returns a list.  Progress uses `multi=True` by default.

**Comment by mrocklin** [comment]
Oh, this is also a deeply nested problem.  One sec, fix coming up.

**Comment by broxtronix** [comment]
Aha!  That's an easy workaround, and does indeed fix the immediate problem.  Beautiful asynchronous progress bars in the notebook are working for me!  Amaze-balls!  

Two minor things:
* Setting `multi = True` didn't seem to work for me yet.  It doesn't generate any progress bar at all in my example computation (same as before, with colormapped images), perhaps because I haven't specified which functions I'd like to track?  That looks like something that the lower level API for `MultiProgress` and `MultiProgressWidget` accept as their `func` arguments?  An ideal default would be to track all unique functions involved with the computation, but I realize that may be a bit difficult to set up.  I'd be totally happy specifying functions to track by hand if that's easiest for now.

* I was having fun creating multiple asynchronous progress bars for the same set of results (of course!), and notice that the progress bars seem to only track portions of the computation that have not yet completed.  That is, if I create a progress bar after half the computation is complete on the cluster, it still starts at zero and counts up to 100%.  I think I'd like it better if it noticed that 50% of the computation was finished, and started at 50% then counted up to 100%.   Again, this is not a super must-have, and I'd be totally content with it as-is.  The ability to monitor computations without locking up notebook execution is already seriously amazing!  Thanks!!

**Comment by mrocklin** [comment]
The default splitting function aligns well with how dask names things.  If you're using dask like naming conventions (tuples, strings with hyphens) then it should come out ok.  I'll take a look at what's going on with `MultiProgressBar`.

Nested futures supported in a recent commit.

**Comment by mrocklin** [comment]
Current policy is to track all keys on which the futures depend that have not yet been completed.  This is less convenient if you start fresh computations all the time and more convenient if you're basing novel computations off of old ones.  I'm not sure which policy is best long term.  It sounds like there is at least value to supporting the "all keys policy."  Will add in a bit

**Comment by broxtronix** [comment]
Definitely no rush on that one.  I think both policies have their merits, and I can adjust my expectations on what the progress bars are displaying.

Regarding the `MultiProgressBar`, I wonder if it may be having trouble because I am nesting pretty much all of my `do()` statements inside list comprehensions:
```
from dask.imperative import do, value

test_images        = [ do(compute_test_image)(z) for z in MOVIE_Z_SAMPLES ]
amplitude_ranges   = [ do(amplitude_range)(im) for im in test_images ]
phase_ranges       = [ do(phase_range)(im) for im in test_images ]

colormapped_images = [ do(colormap_and_combine)(*args) for args in zip(test_images,amplitude_ranges, phase_ranges) ]
```
I need to run out for a bit, but will be glad to continue testing things out later this evening.  Again, thanks for the quick turnaround today!

**Comment by mrocklin** [comment]
By default `dask.do` will name keys by `func-hash` so you'll have names like

    compute_test_image-147287245425

`MultiProgressBar` will split on the hyphen, and grab out the name `compute_test_image`.  Let me clean some things up though.

**Comment by mrocklin** [comment]
Also out for a bit.

**Comment by mrocklin** [comment]
I recommend checking in sometime after late tomorrow morning.

**Comment by broxtronix** [comment]
Sounds great!  Again, no rush at all.  This is super non-critical.  Thanks!

**Comment by mrocklin** [comment]
Oh, if you're in the mood to try things out I'm pretty happy to keep facilitating that and maintain a tight feedback loop.  This feedback is really valuable.

ProgressBars are more sturdy now.  A fair amount of the behavior is now tested.  Additional play-testing is quite welcome.

**Comment by mrocklin** [comment]
Still pushing on this a bit.  Turns out simultaneously managing the Jupyter and distributed event loops is a bit tricky.

**Comment by broxtronix** [comment]
Roger that.  I've been following along and watching the progress.  Just ping me when things converge and I'll happily take it out for a spin!

**Comment by mrocklin** [comment]
With recent changes I think that this is again ready to go.

**Comment by broxtronix** [comment]
Alrighty!  This is definitely very close to working for me.  When I run
```
results = executor.compute(*colormapped_images)
distributed.diagnostics.progress(results, multi = True)
```
I do now get multiple dynamically updating progress bars.  Instead of a few progress bars for `amplitude_range`, `colormap_and_combine` and other functions, I instead see hundreds of them, one for each individual function call.  So, for example, I see hundreds of progress bars for

```
amplitude_range-0130d7d0-fdba-435e-8ee8 [1/1]
amplitude_range-02324839-ac9c-451c-88c2 [1/1]
colormap_and_combine-092a8635-ad06-4362-82c6 [1/1]
colormap_and_combine-0a8e767a-d67f-443b-a4d3 [1/1]
...and many more...

**Comment by mrocklin** [comment]
OK, we'll have to tweak the split key function.  One moment please.

**Comment by mrocklin** [comment]
See https://github.com/blaze/distributed/commit/c7c7c32d5bc19833379a68b0f9ea684ceddf77d6

**Comment by mrocklin** [comment]
Out of curiosity, how did hundreds of progressbars perform?

We should probably group everything after the top ten or so

**Comment by broxtronix** [comment]
Bingo!  Works like a charm now.  Thank you!

Rendering hundreds of progress bars worked surprisingly well.  There was a brief pause of a few seconds as the web browser got its act together for the initial rendering of the new elements of the DOM, but after that it remained surprisingly responsive.  I agree, though... probably best to cap the number of progress bars at 10-20 just to prevent crazy numbers of them.  (Also, I wonder what happens if you use anonymous functions intermixed with `do()` statements... probably these would each get their own progress bar?)

In any case, this is awesome... having the progress bars broken out by function already gives me some additional insight into the real-time execution of the algorithm.  For example, when one function is blocked waiting for results from other functions, its progress bar pausees.  Some functions clearly run faster than others, hinting at functions that might need to be sped up.  Progress for early algorithms finishes up sooner than progress for functions with many dependencies.  

Best of all, these progress bars help me to remain in the notebook context, rather than switching my attention out a separate web console to monitor the status of my jobs.  And I can keep on computing in the notebook while this computation happily & asynchronously cranks away in the background.  Simply. Amazing.

The formatting of the progress bars could use a little improvement, just to justify and align them for better readability.  Some HTML + CSS magic is all that is needed there.  If you want, I'd be willing to try my hand at sprucing up the progress bars.  I could create a new PR after you merge in this one.  It would be a fun (if modest) way for me to get my hands dirty in the `distributed` codebase.

**Comment by mrocklin** [comment]
That sounds great.  I'd be quite happy to leave visual design to others.  If you can bang on this for a little while I'll appreciate it.  I'm going to merge in some other work over at https://github.com/blaze/distributed/pull/38 and then merge this on top of it.  Shooting for end of day.

**Comment by mrocklin** [comment]
And by "bang on this" I mean, subject progressbars to sufficiently varied load to verify that they don't need any fundamental changes and never crash.

**Comment by broxtronix** [comment]
Sounds great.  I'll put the progress bars through a few more tests and see how they do.

**Comment by broxtronix** [comment]
Ok, after testing this out a bit I haven't encountered any huge problems.  The one minor thing I noticed is that the HTML progress bar is suppressed for some reason in cells where you also use the `%%time` cell magic.  Normally you would only need one or the other, so this probably won't come up too often.  Indeed, `%%time` doesn't even make much sense now that functions are asynchronous and returning immediately.  However, this could be a potential point of confusion if users are expecting their progress bar to appear and it doesn't due to cell magic.

Aside from that it all works great.

**Comment by mrocklin** [comment]
This appears to be an IPython notebook thing.  The following cells also don't display the progressbar:

```python
%%time
from ipywidgets import FloatProgress
f = FloatProgress(min=0, max=1)
f.value = 1.0
f
```

**Comment by mrocklin** [comment]
Glad to hear things are working well.  I'll write up some docstrings, maybe a little documentation and then merge this once tests pass.  Thanks gain for your continued feedback and testing on this.

If you do want to play with layout and such, the relevant class is `MultiProgressWidget`, and you're looking for `self.bars`, `self.texts`, and `self.widget`.  Functions like `_update` should give you a pretty good idea of how to manipulate things.

https://github.com/ipython/ipywidgets/blob/master/examples/notebooks/Index.ipynb

**Comment by broxtronix** [comment]
Sounds great.  I'll take a crack at styling the progress bars tomorrow once you've merged all of this in.  Perhaps I'll find a way to work around the cell magic issue and/or I'll file an iPython bug.

Thanks again for investing time in this!

**Comment by mrocklin** [comment]
OK, I'm going to merge this.  As a warning this does introduce a slight race condition.  If I run tests around 100 times I can reproduce it on my laptop.  I think I know what the issue is though; I'll fix this tomorrow in separate work.

**Pull request merged**
