### PR TITLE
Remote scheduler

### PR DESCRIPTION
**Pull request by mrocklin**
We can now connect to a remote scheduler.

    $ dscheduler
    Starting scheduler at 192.168.1.141:8792

```python
In [1]: from distributed import Executor

In [2]: e = Executor('192.168.1.141:8792')

In [3]: x = e.submit(lambda x: x + 1, 10)

In [4]: x.result()
Out[4]: 11
```

### CODE REVIEW

**Comment by mrocklin** [comment]
This is more or less solid.  We can now have a single scheduler process with multiple connecting executors all working concurrently.  Garbage collection doesn't work (key overlaps might result in unwanted releasing of data between executors).

**Comment by minrk** [comment]
Nifty! I'm working on an Executor API for ipyparallel (ipython/ipyparallel#80), so it should be possible to drop in different distributed tools.

**Comment by mrocklin** [comment]
Oh neat.  It'll be good to have several projects around a consistent API.

**Comment by mrocklin** [comment]
Although, I should probably warn more vocally about this, but distributed deviates from pep 3148 in a couple large ways:

1.  submit and map accept futures
2.  map returns futures, not concrete results

**Pull request merged**
