### PR TITLE
Cluster

### PR DESCRIPTION
**Pull request by mrocklin**
cc @broxtronix

### CODE REVIEW

**Comment by mrocklin** [comment]
I needed this for #76

**Comment by mrocklin** [comment]
Planning to merge soon if no comments.

**Comment by mrocklin** [comment]
@broxtronix did you ever run into a problem where you shut down the cluster and restart it again but the port is still blocked?

**Comment by broxtronix** [comment]
Hey @mrocklin, this patch looks pretty much good to me.  If I understand correctly, after this change I will still connect with the executor on the same port, but I'll be connecting to the scheduler rather than the center.
'''
executor = Executor('127.0.0.1:8787')  # Connects to scheduler now instead of center?
'''
I have not had the problem where ports are blocked after shutting down the cluster, at least not in the course of normal usage.  The only time I've experienced this problem is when I accidentally had an errant `dcenter` process running on the command line somewhere that I had forgotten about.  Are you seeing this with `dscheduler` or `dworker` processes?

**Comment by mrocklin** [comment]
With dscheduler.  Possibly I'm not cleaning up the scheduler as cleanly as I was cleaning up the center.  I'll compare the two and see if I can figure it out.

**Pull request merged**
